require "user.launch"
require "user.options"
require "user.keymaps"

spec "user.colorscheme"
spec "user.miniicons"
spec "user.treesitter"
spec "user.mason"
spec "user.schemastore"
spec "user.lspconfig"
spec "user.none-ls"
spec "user.telescope"
spec "user.cmp"
spec "user.autopairs"
spec "user.comment"
--spec "user.netrw"
spec "user.luarocks"
spec "user.fugitive"
spec "user.harpoon"
spec "user.neotest"
--require "user.undotree"

require "user.lazy"
